document.addEventListener('DOMContentLoaded', function() {
    const hamburger = document.getElementById('hamburger');
    const menuheader = document.querySelector('.menuheader');
    const menuItems = document.querySelectorAll('.menuheader a'); // Assuming your menu items are links

    hamburger.addEventListener('click', function() {
        menuheader.classList.toggle('show');
    });

    menuItems.forEach(function(item) {
        item.addEventListener('click', function() {
            menuheader.classList.remove('show');
        });
    });
});
//PREVIEW

let slideIndex = 0; 

function showSlides(n) {
    let slides = document.getElementsByClassName("slides");
    if (n >= slides.length) { slideIndex = 0 }
    if (n < 0) { slideIndex = slides.length - 1 }
    for (let i = 0; i < slides.length; i++) {
        slides[i].classList.remove("active");
    }
    slides[slideIndex].classList.add("active");
}

function plusSlides(n) {
    showSlides(slideIndex += n);
}

showSlides(slideIndex);

//translate
const translations = {
  en: {
    'nav-home': 'Home',
    'nav-skills': 'Skills',
    'nav-portfolio': 'Portfolio',
    'nav-about': 'About',
    'nav-contact': 'Contact',
    'title': 'WebSite - 002',
    'introduction': 'Front-end website designed especially for photographers and editors. This site combines a modern and minimalist aesthetic with robust functionality, ideal for showcasing your services, portfolio, and client testimonials.<br>It is aimed at professionals who want an impactful and effective online presence.<br><br>⚠️All images contained in this project were generated by AI.',
    'view': 'View',
    'features-title': 'Features',
    'developed-in-react': 'Developed in React',
    'front-end': 'Full Front-End',
    'responsive-interface': 'Responsive and functional interface',
    'basic-js-resources': 'Basic JS resources',
    'title-pay':'Buy with PayPal',
    'modelo-front-end':'Front-end Model',
    'modelo-front-end-description':'Description: Ready-made model of a single-page portfolio website, featuring a unique design that directly emphasizes your work. This model does not include secondary pages, ensuring a simple and focused browsing experience.',
    'valor':'Price: R$120.00'
  },
  pt: {
    'nav-home': 'Pagina inicial',
    'nav-skills': 'Skills',
    'nav-portfolio': 'Portfólio',
    'nav-about': 'Sobre',
    'nav-contact': 'Contato',
    'title': 'WebSite - 002',
    'introduction': 'Website front-end projetado especialmente para fotógrafos e editores. Este site combina uma estética moderna e minimalista com uma funcionalidade robusta, ideal para destacar seus serviços, portfólio e recomendações dos clientes.<br>É voltado para profissionais que desejam uma presença online impactante e eficaz.<br><br>⚠️Todas as imagens contidas neste projetos foram geradas por IA.',
    'view': 'Visualizar',
    'features-title': 'Características',
    'developed-in-react': 'Desenvolvido em React',
    'front-end': 'Front-end completo',
    'responsive-interface': 'Interface responsiva e funcional',
    'basic-js-resources': 'Recursos JS básicos',
    'title-pay':'Comprar com PayPal',
    'modelo-front-end':'Modelo Front-end',
    'modelo-front-end-description':'Descrição: Modelo pronto de um site de portfólio de uma única página, com design exclusivo que enfatiza diretamente seu trabalho. Este modelo não inclui páginas secundárias, garantindo uma experiência de navegação simples e focada.',
    'valor':'Valor: R$120.00'

  },
  es: {
    'nav-home': 'Página inicial',
    'nav-skills': 'Habilidades',
    'nav-portfolio': 'Portafolio',
    'nav-about': 'Sobre',
    'nav-contact': 'Contacto',
    'title': 'WebSite - 002',
    'introduction': 'Sitio web de front-end diseñado especialmente para fotógrafos y editores. Este sitio combina una estética moderna y minimalista con una funcionalidad robusta, ideal para mostrar sus servicios, portafolio y testimonios de clientes.<br>Está dirigido a profesionales que desean una presencia en línea impactante y eficaz.<br><br>⚠️Todas las imágenes contenidas en este proyecto fueron generadas por IA.',
    'view': 'Ver',
    'features-title': 'Características',
    'developed-in-react': 'Desarrollado en React',
    'front-end': 'Front-End Completo',
    'responsive-interface': 'Interfaz responsiva y funcional',
    'basic-js-resources': 'Recursos JS básicos',
    'title-pay':'Comprar con PayPal',
    'modelo-front-end':'Modelo Front-end',
    'modelo-front-end-description':'Descripción: Modelo listo de un sitio web de portafolio de una sola página, con un diseño exclusivo que enfatiza directamente su trabajo. Este modelo no incluye páginas secundarias, garantizando una experiencia de navegación simple y enfocada.',
    'valor':'Precio: R$120.00'

  }
};

$(document).ready(function() {
  $('.language-icons a').click(function(e) {
    e.preventDefault();
    const lang = $(this).data('lang');
    $('[data-translate]').each(function() {
      const key = $(this).data('translate');
      $(this).html(translations[lang][key]);
    });
  });
});


//footer
document.addEventListener('DOMContentLoaded', function() {
    const currentYearElement = document.getElementById('currentYear');
    const currentYear = new Date().getFullYear();
    currentYearElement.textContent = currentYear;
});
 
