document.addEventListener('DOMContentLoaded', function() {
    const hamburger = document.getElementById('hamburger');
    const menuheader = document.querySelector('.menuheader');
    const menuItems = document.querySelectorAll('.menuheader a'); // Assuming your menu items are links

    hamburger.addEventListener('click', function() {
        menuheader.classList.toggle('show');
    });

    menuItems.forEach(function(item) {
        item.addEventListener('click', function() {
            menuheader.classList.remove('show');
        });
    });
});
//PREVIEW

let slideIndex = 0;

function showSlides(n) {
    let slides = document.getElementsByClassName("slides");
    if (n >= slides.length) { slideIndex = 0 }
    if (n < 0) { slideIndex = slides.length - 1 }
    for (let i = 0; i < slides.length; i++) {
        slides[i].classList.remove("active");
    }
    slides[slideIndex].classList.add("active");
}

function plusSlides(n) {
    showSlides(slideIndex += n);
}

showSlides(slideIndex);


//translate
const translations = {
    en: {
      'nav-home': 'Home',
      'nav-skills': 'Skills',
      'nav-portfolio': 'Portfolio',
      'nav-about': 'About',
      'nav-contact': 'Contact',
      'title': 'WebSite - 002',
      'introduction': 'Ready-to-use single page business website template, developed in HTML, CSS and JS, with an intuitive design that directly highlights your business sector. This template is carefully designed to emphasize the physical space of the company, introduce the team, showcase the portfolio attractively, and list the services offered by the company. Offering a simple and engaging navigation experience, it eliminates the need for secondary pages, but includes strategic links to social media, contact, and quote forms. All essential details about your company are clearly and accessibly presented in one place. Ideal for businesses seeking an elegant and effective online presence, this template ensures your visitors get a complete and attractive view of everything your company has to offer. <br>The source code is organized, facilitating maintenance, addition of new features, and scalability to meet various needs. <br><br>⚠️ All images in this project were generated by AI.',
      'view': 'View',
      'features-title': 'Features',
      'developed-in-html-js-css': 'Developed in HTML, JS and CSS',
      'front-end': 'Front-end',
      'responsive-interface': 'Responsive and functional interface',
      'basic-js-resources': 'Basic JS resources',
      'title-pay':'Buy with PayPal',
      'modelo-front-end':'Front-end Model',
      'modelo-front-end-description':'Description: One-page portfolio website template with an intuitive design that highlights your work and offers simple, focused navigation.',
      'valor':'Price: R$150.00'
    },
    pt: {
      'nav-home': 'Pagina inicial',
      'nav-skills': 'Skills',
      'nav-portfolio': 'Portfólio',
      'nav-about': 'Sobre',
      'nav-contact': 'Contato',
      'title': 'WebSite - 002',
      'introduction': 'Modelo pronto de site empresarial de uma única página, desenvolvido em HTML, CSS e JS, com um design intuitivo que destaca diretamente o seu ramo de atividade. Este modelo é cuidadosamente projetado para enfatizar o espaço físico da empresa, apresentar a equipe, exibir o portfólio de forma atrativa e listar os serviços oferecidos pela empresa. Com uma experiência de navegação simples e envolvente, ele dispensa páginas secundárias, mas inclui links estratégicos para redes sociais, contato e formulários de orçamento. Todos os detalhes essenciais sobre sua empresa são apresentados de maneira clara e acessível em um só lugar. Ideal para empresas que buscam uma presença online elegante e eficaz, este modelo garante que seus visitantes tenham uma visão completa e atraente de tudo o que sua empresa tem a oferecer.<br>O código-fonte é organizado, facilitando a manutenção, inclusão de novos recursos e a escalabilidade para atender a diversas necessidades. <br><br>⚠️ Todas as imagens contidas neste projetos foram geradas por IA. ',
      'view': 'Visualizar',
      'features-title': 'Características',
      'developed-in-html-js-css': 'Desenvolvido em HTML, JS, e CSS',
      'front-end': 'Front-end',
      'responsive-interface': 'Interface responsiva e funcional',
      'basic-js-resources': 'Recursos JS básicos',
      'title-pay':'Comprar com PayPal',
      'modelo-front-end':'Modelo Front-end',
      'modelo-front-end-description':'Descrição: Modelo de site de portfólio de uma página, com design intuitivo que destaca seu trabalho e oferece navegação simples e focada. ',
      'valor':'Valor: R$150.00'
    },
    es: {
      'nav-home': 'Página inicial',
      'nav-skills': 'Habilidades',
      'nav-portfolio': 'Portafolio',
      'nav-about': 'Sobre',
      'nav-contact': 'Contacto',
      'title': 'WebSite - 002',
      'introduction': 'Modelo de sitio web empresarial de una sola página, desarrollado en HTML, CSS y JS, con un diseño intuitivo que destaca directamente su sector de actividad. Este modelo está cuidadosamente diseñado para enfatizar el espacio físico de la empresa, presentar al equipo, mostrar el portafolio de manera atractiva y listar los servicios ofrecidos por la empresa. Ofreciendo una experiencia de navegación simple y atractiva, elimina la necesidad de páginas secundarias, pero incluye enlaces estratégicos a redes sociales, contacto y formularios de presupuesto. Todos los detalles esenciales sobre su empresa se presentan de manera clara y accesible en un solo lugar. Ideal para empresas que buscan una presencia en línea elegante y eficaz, este modelo asegura que sus visitantes obtengan una visión completa y atractiva de todo lo que su empresa tiene para ofrecer. <br>El código fuente está organizado, facilitando el mantenimiento, la adición de nuevas características y la escalabilidad para satisfacer diversas necesidades. <br><br>⚠️ Todas las imágenes en este proyecto fueron generadas por IA.',
      'view': 'Ver',
      'features-title': 'Características',
      'developed-in-html-js-css': 'Desarrollado en HTML, JS, CSS',
      'front-end': 'Front-end',
      'responsive-interface': 'Interfaz responsiva y funcional',
      'basic-js-resources': 'Recursos JS básicos',
      'title-pay':'Comprar con PayPal',
      'modelo-front-end':'Modelo Front-end',
      'modelo-front-end-description':'Descripción: Plantilla de sitio web de portafolio de una sola página con un diseño intuitivo que destaca su trabajo y ofrece una navegación simple y enfocada.',
      'valor':'Precio: R$150.00'
    }
  };
  
  $(document).ready(function() {
    $('.language-icons a').click(function(e) {
      e.preventDefault();
      const lang = $(this).data('lang');
      $('[data-translate]').each(function() {
        const key = $(this).data('translate');
        $(this).html(translations[lang][key]);
      });
    });
  });
  

//footer
document.addEventListener('DOMContentLoaded', function() {
    const currentYearElement = document.getElementById('currentYear');
    const currentYear = new Date().getFullYear();
    currentYearElement.textContent = currentYear;
});

